
title: Spy School - Academy
email: anton.lafchiev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Coachify delivers learning programmes for sports and event participants - athletes, managers, administrators, officials and coaches - through a series of tailored educational programmes.
baseurl: "/spy-school" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Toneca99
destination: "docs"
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .gitignore
  - scss
  - gulpfile.js
  - package-lock.json
  - package.json
  - .vscode
